name: A SICP Walkthrough
pygments: true
baseurl: "/sicp"
permalink: none

# Custom variables
cat_list: { gettingStarted: "Getting started",
            chapter1: "Chapter 1",
            chapter2: "Chapter 2" }
